import { shadcn } from '@clerk/themes';

export const getClerkAppearance = (basePath: string) => ({
  theme: shadcn,
  cssLayerName: "clerk",
  options: {
    logoPlacement: "inside" as const,
    logoLinkUrl: basePath || "/",
    logoImageUrl: `${window.location.origin}${basePath}/logo.svg`,
  },
  variables: {
    colorPrimary: "hsl(163 60% 25%)",
    colorForeground: "hsl(165 40% 10%)",
    colorMutedForeground: "hsl(165 20% 40%)",
    colorDanger: "hsl(0 70% 45%)",
    colorBackground: "hsl(0 0% 100%)",
    colorInput: "hsl(45 15% 85%)",
    colorInputForeground: "hsl(165 40% 10%)",
    colorNeutral: "hsl(45 15% 85%)",
    fontFamily: "'Inter', sans-serif",
    borderRadius: "0.5rem",
  },
  elements: {
    rootBox: "w-full flex justify-center",
    cardBox: "bg-white rounded-2xl w-[440px] max-w-full overflow-hidden shadow-xl border border-[hsl(45_15%_88%)]",
    card: "!shadow-none !border-0 !bg-transparent !rounded-none",
    footer: "!shadow-none !border-0 !bg-transparent !rounded-none",
    headerTitle: "text-2xl font-bold text-[hsl(165_40%_10%)]",
    headerSubtitle: "text-sm text-[hsl(165_20%_40%)]",
    socialButtonsBlockButtonText: "font-medium text-[hsl(165_40%_10%)]",
    formFieldLabel: "text-sm font-medium text-[hsl(165_40%_10%)]",
    footerActionLink: "font-semibold text-[hsl(163_60%_25%)] hover:underline",
    footerActionText: "text-sm text-[hsl(165_20%_40%)]",
    dividerText: "text-xs text-[hsl(165_20%_40%)] uppercase tracking-wider",
    identityPreviewEditButton: "text-[hsl(163_60%_25%)] hover:underline",
    formFieldSuccessText: "text-sm text-green-600",
    alertText: "text-sm",
    logoBox: "h-12 flex justify-center mb-4",
    logoImage: "h-full w-auto object-contain",
    socialButtonsBlockButton: "border border-[hsl(45_15%_85%)] bg-white hover:bg-[hsl(45_15%_95%)] transition-colors",
    formButtonPrimary: "bg-[hsl(163_60%_25%)] hover:bg-[hsl(163_60%_20%)] text-white font-semibold transition-colors",
    formFieldInput: "bg-white border border-[hsl(45_15%_85%)] text-[hsl(165_40%_10%)] focus:ring-[hsl(163_60%_25%)] rounded-md",
    footerAction: "mt-4 flex items-center justify-center gap-2",
    dividerLine: "bg-[hsl(45_15%_85%)]",
    alert: "rounded-md p-3 mb-4",
    otpCodeFieldInput: "border-[hsl(45_15%_85%)] text-[hsl(165_40%_10%)] focus:border-[hsl(163_60%_25%)]",
    formFieldRow: "mb-4",
    main: "w-full",
  },
});